program = { decl } ;

decl = var_decl
     | fn_decl;

block = "{" { stmt } "}"}

var_decl = ("let" | "const") IDENTIFIER [ ":" type ] "=" expression ";" ;

fn_decl = "fn" IDENTIFIER "(" [ param_list ] ")" [ "->" type ] block ;

param_list = param { "," param } ;

param = IDENTIFIER ":" type ;

struct_decl = "struct" IDENTIFIER "{" { struct_member } "}" ;

struct_member = field_decl
              | function_decl ;

field_decl = IDENTIFIER ":" type [ "," ] ;

type = "i16"
     | "bool"
     | IDENTIFIER
     | "*" type
     | "[" type ";" INTEGER "]" ;

(*
vim: ft=ebnf
*)
