name: tests

on:
  push:
    branches: [main]
    paths: [src]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: rustup update stable

      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
          locked: true

      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-llvm-cov
          locked: true

      - run: |
          cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info --profile ci --ignore-run-fail

      - uses: codecov/codecov-action@v5
        if: ${{!cancelled()}}
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          report_type: coverage
          files: lcov.info
          fail_ci_if_error: false

      - uses: codecov/codecov-action@v5
        if: ${{!cancelled()}}
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          report_type: test_results
          files: ./target/nextest/ci/junit.xml
          fail_ci_if_error: false
